title: BCB Conference Deadlines
description: Bioinformatics and Computational Biology
author: Quan Wei

domain: "quanwei233.github.io"
baseurl: "/bcb-deadlines"

twitter_username: 
twitter_hashtag: 
github_username: quanwei233
github_repo: bcb-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']

theme: jekyll-theme-architect